language: node_js
node_js: 8
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: gYEWFceai5d2HwGvTMN5qpx7B2NVKUFT8aG0yEyZ8PUldavoy3RMHfSBkCmwlR07roWJrMDgva+KRVpTy0Ccq4oRznkIYu719KXIth8CSUTybRD+8pw6abLjTiXfTvWDroo7D5BE5Ieses0W2oNjgR9gOT2BCBdNhIV0OR+MMvmx4heDarzBYuJADs1AABdRXZzXa2LWn6XxzK9/xctA5FkjwDaKmjzaNmj7xoCaWYjgu/tbnZVBaWSmwY6lBESZEFnSjZlXQqoh5Nu8y4s7YpG9u7pC5cV4jnFAY3DZxx2hDlQUv/7sH6ZW8xkQ9fvhOAJ7lTwW2e5SZx/TfHuHdBHJldfYaB9+6mFJY4VAPFQZQVMXDQmwstdkP+6AQkcV68tRmN1N6JvENDiX5zXwHLqH7mne5UH8yqw/vCx31gFnLGRQWc/1T4gFxYlUlnjx+I0tYNF3zuW828acu9f3IFZmqx5A+bJ/xgWBzx35YENEHHCcU0v5PvDn8jEmjR/hyCaZaSMfLcZuNyaxdXe4NTigGivgRZYXjvq6+VtwtfR1Y27K23i5JuEA37hI+ZvXrJLibjLW88fQ55p/x3fMe16GBeWv4i6HZmc01mASpblZIWTKIlUm/1HxS2lY4zsNFgLPv+WAQEIUlykLMNIrm0ZONCrgdIUrLdwRaa7AbCo=